version: "3.8"

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - 5001:5001
    restart: always

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    restart: always

  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A make_celery worker --loglevel=info
    depends_on:
      - redis
    restart: always

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A make_celery beat --loglevel=info
    depends_on:
      - redis
    restart: always

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    restart: always
